
				<table class="table-condensed">
           	
<!-- Issuer -->
			    <tr class="row">
					<td align="right"><strong><?php echo $this->translate('Issuer', 'ppit-expense', $context->getLocale()) ?></strong></td>
					<td><?php echo $reportRow->agent_n_fn ?></td>
				</tr>
           	
<!-- Approver -->
<?php if ($reportRow->approver_id) : ?>
				<tr class="row">
					<td align="right"><strong><?php echo $this->translate('Approver', 'ppit-user', $context->getLocale()) ?></strong></td>
					<td><?php echo $reportRow->approver_n_fn ?></td>
				</tr>
<?php endif;?>

<!-- Document name -->
<?php if ($reportRow->document_name) : ?>
				<tr class="row">
					<td align="right"><strong><?php echo $this->translate('Documentary evidence', 'ppit-expense', $context->getLocale()) ?></strong></td>
					<td><a href="<?php echo $this->url('link/download', array('id' => $reportRow->document_id));?>"><?php echo $reportRow->document_name ?></a></td>
				</tr>
<?php endif;?>
				
<!-- Expense date -->
			    <tr class="row">
					<td align="right"><strong><?php echo $this->translate('Expense date', 'ppit-expense', $context->getLocale()) ?></strong></td>
					<td><?php echo $currentUser->decodeDate($reportRow->expense_date) ?></td>
				</tr>

<!-- Approval date -->
<?php if ($reportRow->approval_date) : ?>
			    <tr class="row">
					<td align="right"><strong><?php echo $this->translate('Approved on', 'ppit-expense', $context->getLocale()) ?></strong></td>
					<td><?php echo $currentUser->decodeDate($reportRow->approval_date) ?></td>
				</tr>
<?php endif;?>

<!-- Registration date -->
<?php if ($reportRow->registration_date) : ?>
				<tr class="row">
					<td align="right"><strong><?php echo $this->translate('Registered on', 'ppit-expense', $context->getLocale()) ?></strong></td>
					<td><?php echo $currentUser->decodeDate($reportRow->registration_date) ?></td>
				</tr>
<?php endif;?>

<!-- Category -->
			    <tr class="row">
					<td align="right"><strong><?php echo $this->translate('Category', 'ppit-core', $context->getLocale()) ?></strong></td>
					<td><?php echo $this->translate($reportRow->category, 'ppit-expense', $context->getLocale()) ?></td>
				</tr>

<!-- Justification -->
<?php if ($reportRow->justification) : ?>
				<tr class="row">
					<td align="right"><strong><?php echo $this->translate('Customer name', 'ppit-expense', $context->getLocale()) ?></strong></td>
					<td><?php echo $this->translate($reportRow->justification, 'ppit-expense', $context->getLocale()) ?></td>
				</tr>
<?php endif;?>

				<tr class="row"><td colspan="2">&nbsp;</td></tr>

<?php if ($reportRow->category == 'Mileage allowance') : ?>
				
<!-- Horsepower -->
				<tr class="row">
					<td align="right"><strong><?php echo $this->translate('Horsepower', 'ppit-expense', $context->getLocale()) ?></strong></td>
					<td><?php echo $reportRow->horsepower ?></td>
				</tr>

<!-- Distance -->
				<tr class="row">
					<td align="right"><strong><?php echo $this->translate('Number of miles', 'ppit-expense', $context->getLocale()) ?></strong></td>
					<td><?php echo $reportRow->quantity ?></td>
				</tr>

<?php else : ?>
				
<!-- Including tax amount -->
				<tr class="row">
					<td align="right"><strong><?php echo $this->translate('Incl. tax amount', 'ppit-expense', $context->getLocale()) ?></strong></td>
					<td><?php echo $currentUser->formatFloat($reportRow->including_vat_amount, 2).' '.$currentUser->currency_symbol ?></td>
				</tr>
				
<!-- VAT amount -->
<?php if ($reportRow->vat_rate_1) : ?>
				<tr class="row">
					<td align="right"><?php echo $this->translate('Including VAT', 'ppit-expense', $context->getLocale()) ?> <?php //echo $this->translate($settings['vatRates'][$reportRow->vat_rate_1], 'ppit-expense', $context->getLocale()) ?></td>
					<td><?php echo $currentUser->formatFloat($reportRow->amount_vat_1, 2).' '.$currentUser->currency_symbol ?></td>
				</tr>
<?php endif;?>

<?php endif;?>

<!-- Capped amount -->
				<tr class="row">
					<td align="right"><strong><?php echo $this->translate('Repaid', 'ppit-expense', $context->getLocale()) ?></strong></td>
					<td><strong><?php echo $currentUser->formatFloat($reportRow->capped_amount, 2).' '.$currentUser->currency_symbol ?></strong></td>
				</tr>

				<tr class="row">&nbsp;</tr>

				<tr class="row"><td colspan="2">&nbsp;</td></tr>

				</table>

<?php if ($reportRow->audit) : ?> 
<!-- Audit -->
				
				<div class="panel panel-default">
		            <div class="panel-heading">
						<strong><?php echo $this->translate($this->translate('Historical', 'ppit-core', $context->getLocale()));?></strong>
		            </div>
					<div class="panel-body">
	<?php foreach ($reportRow->audit as $comment) : ?>
						<div class="row">
							<div class="col-md-12">
								<strong><?php echo $currentUser->decodeDate($comment->date) ?>:</strong>&nbsp;
								<?php echo $this->translate($comment->status, 'ppit-expense', $context->getLocale()) ?>&nbsp;
								(<?php echo $comment->user ?>)
							</div>
						</div>
						<div class="row">
							<div class="col-md-2" align="right">&nbsp;</div>
							<div class="col-md-10">
								<em><?php echo $comment->comment ?></em></div>
						</div>
	<?php endforeach;?>
					</div>
				</div>
<?php endif;?>
