<div class="panel panel-default">
	<div class="panel-heading" style="background:  <?php echo $context->getConfig('styleSheet')['panelHeadingBackground'] ?>; color: <?php echo $context->getConfig('styleSheet')['panelHeadingColor'] ?>">
		<strong><?php echo ($expense->id) ? $this->translate('Detail', 'ppit-core', $context->getLocale()) : $this->translate('Add', 'ppit-core', $context->getLocale()) ?></strong>
 		<div class="btn-group pull-right">
			<button type="button" class="btn btn-default" title="<?php echo $this->translate('Return to list', 'ppit-core', $context->getLocale()) ?>" id="remove-anchor">
				<span class="glyphicon glyphicon-remove"></span>
			</button>
 		 </div>
	</div>
	<div class="panel-body">

<?php if ($context->getConfig('expense/detail')['displayAudit'] && $expense->id) : ?>
<!-- Display the audit -->
		<?php echo $this->translate('History', 'ppit-core', $context->getLocale()) ?> (<a id="audit-label" href="#"><?php echo $this->translate('Show', 'ppit-core', $context->getLocale()) ?></a>)
		<div id="audit-panel" class="panel panel-default">
			<div class="panel-body">
	<?php foreach ($expense->audit as $comment) : ?>
				<div class="row">
					<div class="col-md-12">
						<strong><?php echo $context->decodeDate(substr($comment['time'], 0, 10)).substr($comment['time'], 10) ?>:</strong>&nbsp;
						<?php if (array_key_exists('status', $comment)) echo $context->getconfig('expense')['properties']['status'][$comment['status']][$context->getLocale()] ?>&nbsp;
						(<?php echo $comment['n_fn'] ?>)
					</div>
				</div>
				<div class="row">
					<div class="col-md-2" align="right">&nbsp;</div>
					<div class="col-md-10"><em><?php if (array_key_exists('comment', $comment)) echo $comment['comment'] ?></em></div>
				</div>
	<?php endforeach;?>
			</div>
		</div>
		<div>&nbsp;</div>
		<div>
<?php endif;?>

		<div class="tab-content">
			<div class="tab-pane fade in active" id="expense-update-panel"></div>
		</div>
	</div>
	