<?php
	echo $this->partial('/partials/menu');
    $title = $this->translate('Expense reports', 'ppit-expense', $context->getLocale());
	$this->headTitle($title);
?>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
		<div class="panel panel-default">
            <div class="panel-heading">
				<strong><?php echo $this->translate('Expense reports', 'ppit-expense', $context->getLocale());?></strong>
            </div>
           	<div class="panel-body">
           	
<!-- Header -->
				<table class="table-condensed">
					<tr>
						<td>
							<a href="<?php echo $this->url('reportRow/index');?>"><?php echo $this->translate('My expense reports', 'ppit-expense', $context->getLocale()) ?></a>
							&nbsp;&nbsp;|&nbsp;&nbsp;
							<a href="<?php echo $this->url('report/todo');?>"><?php echo $this->translate('To be registered', 'ppit-expense', $context->getLocale()) ?></a>
							&nbsp;&nbsp;|&nbsp;&nbsp;
							<a href="<?php echo $this->url('report/export');?>"><?php echo $this->translate('CSV export', 'ppit-core', $context->getLocale()) ?></a>
						</td>
					</tr>
					<tr><td>&nbsp;</td></tr>
				</table>

<!-- Rows -->
				
				
				<table class="table table-striped">
					<tr>
						<td align="center"><strong><a href="<?php echo $this->url($this->route, array('action' => 'index')) ?>
															?major=period
															<?php if ($major == 'period' && $dir =='ASC') echo '&dir=DESC'; else echo '&dir=ASC' ?>">
							<?php echo $this->translate('Period', 'ppit-expense', $context->getLocale());?></strong></td>
						<td align="center"><strong><a href="<?php echo $this->url($this->route, array('action' => 'index')) ?>
															?major=agent_n_fn
															<?php if ($major == 'agent_n_fn' && $dir =='ASC') echo '&dir=DESC'; else echo '&dir=ASC' ?>">
							<?php echo 'Agent' ?></strong></td>
					</tr>
<?php foreach ($reports as $report) : ?>
					<tr>
						<td align="left"><?php echo $report->period ?></td>
						<td align="left"><a href="<?php echo $this->url('report/detail', array('period' => $report->period, 'owner_id' => $report->owner_id))?>"><?php echo $report->agent_n_fn ?></td>
					</tr>
<?php endforeach; ?>
				</table>
			</div>
		</div>
	</div>
</div>
