<?php
	$title = $this->translate('Login');
	$this->headTitle($title);
?>
<div>
    <a target="_blank" href="https://www.p-pit.fr"><img width="300" src="<?php echo $this->basePath('images/ppit-300-baseline.png') ?>" width="300" alt="<?php $this->translate('CIT Logo') ?>"></a>
</div>
<div>&nbsp;</div>
<div class="row">
    <div class="col-md-4 col-md-offset-4">
		<div class="panel panel-default">
            <div class="panel-heading">
				<strong><?php echo $this->translate('New password');?></strong>
            </div>
           	<div class="panel-body">

<!-- Form opening tag -->
				<form action="<?php echo $this->url('reportAdmin/initpassword', array('id' => $id)) ?>" method="post" name="initpassword" class="form-horizontal" enctype="form-data" id="initpassword" onSubmit="return checkForm()">

<!--  CSRF -->
<?php $element = $csrfForm->get('csrf') ?>
				    <div class="form-group">
						<?php echo $this->formElement($element) ?>
<?php if ($this->formElementErrors($element)) : ?>
						<div class="col-sm-12"><p class="help-block"><?php echo $this->translate('The form has expired, please input again', 'ppit-core', $context->getLocale()) ?></p></div>
<?php endif;?>
					</div>
					
<!-- Password -->
				    <div class="form-group" id="password_group">
 						<label class="col-sm-5 control-label">* <?php echo $this->translate('Password') ?></label>
				    	<div class="col-sm-7">
							<input type="password" name="password" id="password" class="form-control"">
						</div>
						<div class="col-sm-12"><p class="help-block" id="password_error"></p></div>
					</div>

<!-- Password (2nd) -->
				    <div class="form-group" id="password2_group">
 						<label class="col-sm-5 control-label">* <?php echo $this->translate('Confirm') ?></label>
				    	<div class="col-sm-7">
							<input type="password" name="password2" id="password2" class="form-control"">
						</div>
						<div class="col-sm-12"><p class="help-block" id="password2_error"></p></div>
					</div>
					
<!-- Submit button -->
				    <div class="form-group">
						<div class="col-sm-2">&nbsp;</div>
						<div class="col-sm-10">
							<input name="submit" type="submit" id="submitbutton" class="btn btn-primary" value="<?php echo $this->translate('Update') ?>">
							&nbsp;&nbsp;
							<a href="<?php echo $this->url('user') ?>"><?php echo $this->translate('Cancel') ?></a>
						</div>
					</div>
				</form>
   			</div>
		</div>
	</div>
</div>

<script>

function renderElement(elementId, error) {

	if (error) {
		document.getElementById(elementId + "_group").className = "form-group has-error";
		document.getElementById(elementId + "_error").innerHTML = error;
		document.getElementById(elementId + "_error").style.display = "block";
		document.getElementById(elementId).focus();
	}
	else {
		document.getElementById(elementId + "_group").className = "form-group";
		document.getElementById(elementId + "_error").innerHTML = "";
    	document.getElementById(elementId + "_error").style.display = "none";
	}
}

// The elements are checked last to first so the focus is positionned on the first element on error
function checkForm() 
{
	var validity = true;

// Password
	var password = document.getElementById("password").value;
    var passwordFormat = /^(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}$/;
    if (!passwordFormat.test(password)) {
	    renderElement("password", "<?php echo $this->translate('The password should be at least 8 characters long and contain 1 uppercase letter and 1 digit') ?>");
    	validity = false;
    }
    else {
        renderElement("password", null);
        	
// Password (2nd)
        password2 = document.getElementById("password2").value;
        if (password2 != password) {
        	renderElement("password2", "<?php echo $this->translate('Both passwords should be the same one') ?>");
        	validity = false;
        }
        else {
        	renderElement("password2", null);
        }
	}

	return validity;
}

</script>
